### PR TITLE
test F34 upgrade with disabled auditd

### PR DESCRIPTION
**Pull request by jhrozek**
this works for me locally, let's see what Ci says

### CODE REVIEW

**Comment by JAORMX** [comment]
Fedora didn't like auditd to be turned off it seems

**Comment by JAORMX** [comment]
Oho! This got the secure-e2e test working

**Comment by JAORMX** [comment]
Seems the job is no longer fetching the seccomp profile correctly. You could make that step optional and we could fix that later if you want. The test itself passed.

**Comment by jhrozek** [comment]
> Seems the job is no longer fetching the seccomp profile correctly. You could make that step optional and we could fix that later if you want. The test itself passed.

It's super weird, I can't make the seccomp generation work even though I clearly had to generate the profile somehow. I don't remember what I did to generate it, maybe I just ran the machine in permissive mode. So far I commented out the steps..how do I make them optional?

btw I also trimmed the autogenerated seccomp profile somewhat, removed keyctl, mount, umount, setuid and other calls which the app never needs and might have a large attack surface.

**Pull request merged**
