### PR TITLE
GH: Use Ubuntu 20.04 as GH runners and update SELinux policy

### PR DESCRIPTION
**Pull request by jhrozek**
Let's see if this version can build the Fedora container with podman..

### CODE REVIEW

**Comment by JAORMX** [comment]
@JAORMX seems that we need to update the security policies as part of this PR.

**Comment by jhrozek** [comment]
On Mon, Nov 08, 2021 at 08:49:15AM -0800, Juan Osorio Robles wrote:
> @JAORMX seems that we need to update the security policies as part of this PR.

Yes, let me try to update them, but I'm happy that upgrading Ubuntu
helped.

(btw the reason I thought about upgrading the base OS was that I was
seeing the same error locally on my ancient F-32, but not when running
podman build in a F-35 VM. Yes, I need to upgrade, I know)

**Comment by jhrozek** [comment]
So the new patches are autogenerated policies from a local run. Let's see how they work in CI..but even if they do, let's not push them yet, there are some things in the autogenerated policies that are weird.

**Comment by jhrozek** [comment]
@JAORMX this should be safe to merge now that SPO has been updated

**Pull request merged**
